(function (root) {
  var ATC = root.ATC || (root.ATC = {});

  ATC.ROLES = [
    { id: "delegate", vi: "Đại biểu", en: "Delegate", hint: "Can thiệp / intervention" },
    { id: "rapporteur", vi: "Báo cáo viên", en: "Rapporteur", hint: "Trả lời Q&A" },
    { id: "chair", vi: "Chủ tọa", en: "Chair", hint: "Điều hành phiên" },
    { id: "interpreter", vi: "Phiên dịch", en: "Interpreter", hint: "Bám thuật ngữ" }
  ];

  ATC.CONTEXTS = [
    { id: "conference", vi: "Hội nghị / plenary", en: "Conference" },
    { id: "workshop", vi: "Hội thảo / workshop", en: "Workshop" },
    { id: "icao_course", vi: "Khóa học ICAO", en: "ICAO course" },
    { id: "internal", vi: "Họp nội bộ", en: "Internal meeting" }
  ];

  ATC.AFFILIATIONS = [
    { id: "vatm", vi: "VATM", en: "Vietnam Air Traffic Management Corporation (VATM)" },
    { id: "norats", vi: "VATM — NORATS", en: "VATM Northern Region (NORATS)" },
    { id: "sorats", vi: "VATM — SORATS", en: "VATM Southern Region (SORATS)" },
    { id: "mirats", vi: "VATM — MIRATS", en: "VATM Middle Region (MIRATS)" },
    { id: "atfmc", vi: "VATM — ATFMC", en: "VATM ATFM Centre" },
    { id: "vnaic", vi: "VNAIC", en: "Vietnam Aeronautical Information Centre (VNAIC)" },
    { id: "attech", vi: "ATTECH", en: "Air Traffic Technical Company (ATTECH)" },
    { id: "caav", vi: "Cục Hàng không Việt Nam", en: "Civil Aviation Authority of Viet Nam (CAAV)" },
    { id: "delegation", vi: "Đoàn Việt Nam", en: "the Delegation of Viet Nam" }
  ];

  ATC.SESSION_TOPICS = [
    { id: "auto", vi: "Tự nhận chủ đề", en: "Auto-detect" },
    { id: "sms_frms", vi: "SMS / FRMS", en: "SMS / FRMS" },
    { id: "swim", vi: "SWIM / dữ liệu", en: "SWIM / data" },
    { id: "pbn", vi: "PBN / CCO / CDO", en: "PBN / CCO / CDO" },
    { id: "atfm_capacity", vi: "ATFM / năng lực", en: "ATFM / capacity" },
    { id: "staffing", vi: "Định biên / CBTA", en: "Staffing / CBTA" },
    { id: "language", vi: "Tiếng Anh ICAO", en: "Language proficiency" },
    { id: "cns", vi: "CNS / giám sát", en: "CNS / surveillance" },
    { id: "safety", vi: "Just culture / SPI", en: "Just culture / SPI" },
    { id: "acdm", vi: "A-CDM / AMAN", en: "A-CDM / AMAN" },
    { id: "general", vi: "Chung / khác", en: "General" }
  ];

  ATC.TERMS = [
    { abbr: "ATS", en: "air traffic services", vi: "dịch vụ không lưu" },
    { abbr: "ATM", en: "air traffic management", vi: "quản lý không lưu" },
    { abbr: "ATC", en: "air traffic control", vi: "kiểm soát không lưu" },
    { abbr: "ATCO", en: "air traffic controller", vi: "kiểm soát viên không lưu" },
    { abbr: "ATSEP", en: "air traffic safety electronics personnel", vi: "nhân viên kỹ thuật an toàn không lưu" },
    { abbr: "ANS", en: "air navigation services", vi: "dịch vụ dẫn đường hàng không" },
    { abbr: "ANSP", en: "air navigation service provider", vi: "nhà cung cấp dịch vụ dẫn đường hàng không" },
    { abbr: "SMS", en: "safety management system", vi: "hệ thống quản lý an toàn" },
    { abbr: "QMS", en: "quality management system", vi: "hệ thống quản lý chất lượng" },
    { abbr: "FRMS", en: "fatigue risk management system", vi: "hệ thống quản lý rủi ro mệt mỏi" },
    { abbr: "ATFM", en: "air traffic flow management", vi: "quản lý luồng không lưu" },
    { abbr: "ATFMC", en: "air traffic flow management centre", vi: "trung tâm quản lý luồng không lưu" },
    { abbr: "SWIM", en: "system-wide information management", vi: "quản lý thông tin toàn hệ thống" },
    { abbr: "PBN", en: "performance-based navigation", vi: "dẫn đường dựa trên hiệu năng" },
    { abbr: "RNAV", en: "area navigation", vi: "dẫn đường khu vực" },
    { abbr: "RNP", en: "required navigation performance", vi: "hiệu năng dẫn đường yêu cầu" },
    { abbr: "CDO", en: "continuous descent operations", vi: "khai thác hạ độ cao liên tục" },
    { abbr: "CCO", en: "continuous climb operations", vi: "khai thác leo cao liên tục" },
    { abbr: "A-CDM", en: "airport collaborative decision-making", vi: "ra quyết định cộng tác tại sân bay" },
    { abbr: "AMAN", en: "arrival manager", vi: "hệ thống quản lý tàu bay đến" },
    { abbr: "DMAN", en: "departure manager", vi: "hệ thống quản lý tàu bay khởi hành" },
    { abbr: "TMA", en: "terminal control area", vi: "khu vực kiểm soát tiếp cận" },
    { abbr: "FIR", en: "flight information region", vi: "vùng thông báo bay" },
    { abbr: "ACC", en: "area control centre", vi: "trung tâm kiểm soát đường dài" },
    { abbr: "APP", en: "approach control", vi: "kiểm soát tiếp cận" },
    { abbr: "TWR", en: "aerodrome control tower", vi: "đài kiểm soát tại sân" },
    { abbr: "GND", en: "ground control", vi: "kiểm soát mặt đất" },
    { abbr: "FIS", en: "flight information service", vi: "dịch vụ thông báo bay" },
    { abbr: "ALR", en: "alerting service", vi: "dịch vụ báo động" },
    { abbr: "RCC", en: "rescue coordination centre", vi: "trung tâm phối hợp tìm kiếm cứu nạn" },
    { abbr: "SAR", en: "search and rescue", vi: "tìm kiếm cứu nạn" },
    { abbr: "MET", en: "meteorological service", vi: "dịch vụ khí tượng hàng không" },
    { abbr: "AIS", en: "aeronautical information service", vi: "dịch vụ thông báo tin tức hàng không" },
    { abbr: "AIP", en: "Aeronautical Information Publication", vi: "Tập thông báo tin tức hàng không" },
    { abbr: "NOTAM", en: "Notice to Airmen", vi: "điện văn NOTAM" },
    { abbr: "OLDI", en: "on-line data interchange", vi: "trao đổi dữ liệu trực tuyến" },
    { abbr: "AIDC", en: "ATS interfacility data communication", vi: "liên lạc dữ liệu giữa các cơ sở ATS" },
    { abbr: "CPDLC", en: "controller–pilot data link communications", vi: "liên lạc dữ liệu kiểm soát viên–phi công" },
    { abbr: "ADS-B", en: "automatic dependent surveillance — broadcast", vi: "giám sát phụ thuộc tự động — phát" },
    { abbr: "ADS-C", en: "automatic dependent surveillance — contract", vi: "giám sát phụ thuộc tự động — hợp đồng" },
    { abbr: "MLAT", en: "multilateration", vi: "đa điểm đo khoảng cách" },
    { abbr: "WAM", en: "wide area multilateration", vi: "đa điểm đo diện rộng" },
    { abbr: "PSR", en: "primary surveillance radar", vi: "ra-đa giám sát sơ cấp" },
    { abbr: "SSR", en: "secondary surveillance radar", vi: "ra-đa giám sát thứ cấp" },
    { abbr: "CNS", en: "communications, navigation and surveillance", vi: "thông tin, dẫn đường và giám sát" },
    { abbr: "GANP", en: "Global Air Navigation Plan", vi: "Kế hoạch dẫn đường hàng không toàn cầu" },
    { abbr: "ASBU", en: "Aviation System Block Upgrades", vi: "nâng cấp khối hệ thống hàng không" },
    { abbr: "FF-ICE", en: "flight and flow information for a collaborative environment", vi: "thông tin bay và luồng cho môi trường cộng tác" },
    { abbr: "TBO", en: "trajectory-based operations", vi: "khai thác theo quỹ đạo" },
    { abbr: "CBTA", en: "competency-based training and assessment", vi: "huấn luyện và đánh giá theo năng lực" },
    { abbr: "OJT", en: "on-the-job training", vi: "huấn luyện tại vị trí" },
    { abbr: "OJTI", en: "on-the-job training instructor", vi: "huấn luyện viên tại vị trí" },
    { abbr: "LPR", en: "language proficiency requirements", vi: "yêu cầu trình độ ngôn ngữ" },
    { abbr: "SPI", en: "safety performance indicator", vi: "chỉ số hiệu suất an toàn" },
    { abbr: "SPT", en: "safety performance target", vi: "mục tiêu hiệu suất an toàn" },
    { abbr: "KPI", en: "key performance indicator", vi: "chỉ số hiệu suất then chốt" },
    { abbr: "LoA", en: "letter of agreement", vi: "thư thỏa thuận" },
    { abbr: "LoC", en: "letter of coordination", vi: "thư hiệp đồng" },
    { abbr: "SID", en: "standard instrument departure", vi: "đường khởi hành bằng thiết bị tiêu chuẩn" },
    { abbr: "STAR", en: "standard instrument arrival", vi: "đường đến bằng thiết bị tiêu chuẩn" },
    { abbr: "IAP", en: "instrument approach procedure", vi: "thủ tục tiếp cận bằng thiết bị" },
    { abbr: "RVSM", en: "reduced vertical separation minimum", vi: "phân cách thẳng đứng giảm thiểu" },
    { abbr: "GBAS", en: "ground-based augmentation system", vi: "hệ thống tăng cường dựa trên mặt đất" },
    { abbr: "SBAS", en: "satellite-based augmentation system", vi: "hệ thống tăng cường dựa trên vệ tinh" },
    { abbr: "CAPA", en: "corrective and preventive action", vi: "hành động khắc phục và phòng ngừa" },
    { abbr: "MOR", en: "mandatory occurrence report", vi: "báo cáo sự cố bắt buộc" },
    { abbr: "VATM", en: "Vietnam Air Traffic Management Corporation", vi: "Tổng công ty Quản lý bay Việt Nam" },
    { abbr: "CAAV", en: "Civil Aviation Authority of Viet Nam", vi: "Cục Hàng không Việt Nam" },
    { abbr: "ICAO", en: "International Civil Aviation Organization", vi: "Tổ chức Hàng không Dân dụng Quốc tế" },
    { abbr: "NORATS", en: "Northern Region Air Traffic Services", vi: "Công ty Quản lý bay miền Bắc" },
    { abbr: "SORATS", en: "Southern Region Air Traffic Services", vi: "Công ty Quản lý bay miền Nam" },
    { abbr: "MIRATS", en: "Middle Region Air Traffic Services", vi: "Công ty Quản lý bay miền Trung" },
    { en: "fatigue risk management", vi: "quản lý rủi ro mệt mỏi" },
    { en: "fatigue management", vi: "quản lý mệt mỏi" },
    { en: "just culture", vi: "văn hóa công bằng" },
    { en: "safety assurance", vi: "bảo đảm an toàn" },
    { en: "safety risk management", vi: "quản lý rủi ro an toàn" },
    { en: "safety policy", vi: "chính sách an toàn" },
    { en: "safety promotion", vi: "thúc đẩy an toàn" },
    { en: "change management", vi: "quản lý thay đổi" },
    { en: "safety case", vi: "hồ sơ an toàn" },
    { en: "aeronautical study", vi: "nghiên cứu hàng không" },
    { en: "declared capacity", vi: "năng lực công bố" },
    { en: "sector capacity", vi: "năng lực khu vực" },
    { en: "runway throughput", vi: "năng suất đường cất hạ cánh" },
    { en: "watch schedule", vi: "lịch kíp trực" },
    { en: "roster", vi: "lịch ca kíp" },
    { en: "duty time", vi: "thời gian làm nhiệm vụ" },
    { en: "time-in-position", vi: "thời gian trực vị trí" },
    { en: "night duty", vi: "ca đêm" },
    { en: "on-call duty", vi: "trực chờ" },
    { en: "unit endorsement", vi: "năng định đơn vị" },
    { en: "language proficiency", vi: "trình độ ngôn ngữ" },
    { en: "operational capacity", vi: "năng lực khai thác" },
    { en: "staffing level", vi: "định biên" },
    { en: "staffing levels", vi: "định biên nhân sự" },
    { en: "predictive", vi: "dự báo" },
    { en: "proactive", vi: "chủ động" },
    { en: "reactive", vi: "phản ứng" },
    { en: "self-report", vi: "tự báo cáo" },
    { en: "fit for duty", vi: "đủ điều kiện nhận nhiệm vụ" },
    { en: "hazard identification", vi: "nhận diện mối nguy" },
    { en: "risk mitigation", vi: "giảm thiểu rủi ro" },
    { en: "safety occurrence", vi: "sự cố an toàn" },
    { en: "runway incursion", vi: "xâm nhập đường cất hạ cánh" },
    { en: "runway excursion", vi: "trượt khỏi đường cất hạ cánh" },
    { en: "loss of separation", vi: "mất phân cách" },
    { en: "airprox", vi: "uy hiếp va chạm trên không" },
    { en: "handover", vi: "bàn giao ca" },
    { en: "position relief", vi: "thay ca tại vị trí" },
    { en: "controller workload", vi: "tải việc của kiểm soát viên" },
    { en: "traffic complexity", vi: "độ phức tạp dòng không lưu" },
    { en: "flow measure", vi: "biện pháp điều hòa luồng" },
    { en: "ground delay programme", vi: "chương trình chậm dưới đất" },
    { en: "miles-in-trail", vi: "giãn cách theo hải lý" },
    { en: "slot allocation", vi: "phân bổ slot" },
    { en: "collaborative decision-making", vi: "ra quyết định cộng tác" },
    { en: "information exchange", vi: "trao đổi thông tin" },
    { en: "data quality", vi: "chất lượng dữ liệu" },
    { en: "interoperability", vi: "khả năng liên thông" },
    { en: "fixm", enDisplay: "FIXM", vi: "mô hình thông tin bay" },
    { en: "aixm", enDisplay: "AIXM", vi: "mô hình thông tin hàng không" },
    { en: "wxxm", enDisplay: "WXXM", vi: "mô hình thông tin thời tiết" },
    { en: "controller", vi: "kiểm soát viên" },
    { en: "controllers", vi: "các kiểm soát viên" },
    { en: "pilot", vi: "phi công" },
    { en: "pilots", vi: "các phi công" },
    { en: "aircraft", vi: "tàu bay" },
    { en: "airline", vi: "hãng hàng không" },
    { en: "airlines", vi: "các hãng hàng không" },
    { en: "airport", vi: "sân bay" },
    { en: "airports", vi: "các sân bay" },
    { en: "airspace", vi: "không phận" },
    { en: "aerodrome", vi: "sân bay" },
    { en: "runway", vi: "đường cất hạ cánh" },
    { en: "taxiway", vi: "đường lăn" },
    { en: "apron", vi: "sân đỗ" },
    { en: "approach", vi: "tiếp cận" },
    { en: "departure", vi: "khởi hành" },
    { en: "arrival", vi: "đến" },
    { en: "clearance", vi: "phép ATC" },
    { en: "holding", vi: "chờ vòng" },
    { en: "vectoring", vi: "dẫn hướng" },
    { en: "separation", vi: "phân cách" },
    { en: "spacing", vi: "giãn cách" },
    { en: "sector", vi: "khu vực" },
    { en: "sectors", vi: "các khu vực" },
    { en: "traffic", vi: "không lưu" },
    { en: "watch", vi: "kíp trực" },
    { en: "shift", vi: "ca" },
    { en: "occurrence", vi: "sự cố" },
    { en: "incident", vi: "sự cố" },
    { en: "accident", vi: "tai nạn" },
    { en: "hazard", vi: "mối nguy" },
    { en: "surveillance", vi: "giám sát" },
    { en: "navigation", vi: "dẫn đường" },
    { en: "radar", vi: "ra-đa" },
    { en: "altitude", vi: "độ cao" },
    { en: "flight", vi: "chuyến bay" },
    { en: "operations", vi: "khai thác" },
    { en: "operation", vi: "khai thác" },
    { en: "operational", vi: "về khai thác" },
    { en: "procedure", vi: "thủ tục" },
    { en: "procedures", vi: "các thủ tục" },
    { en: "performance", vi: "hiệu năng" },
    { en: "capacity", vi: "năng lực" },
    { en: "delay", vi: "chậm" },
    { en: "delays", vi: "chậm chuyến" },
    { en: "demand", vi: "nhu cầu" },
    { en: "flow", vi: "luồng" },
    { en: "slot", vi: "slot" },
    { en: "workload", vi: "tải việc" },
    { en: "complexity", vi: "độ phức tạp" },
    { en: "staffing", vi: "định biên" },
    { en: "endorsement", vi: "năng định" },
    { en: "competency", vi: "năng lực chuyên môn" },
    { en: "proficiency", vi: "trình độ" },
    { en: "phraseology", vi: "thuật ngữ vô tuyến" },
    { en: "instructor", vi: "huấn luyện viên" },
    { en: "supervisor", vi: "ca trưởng" },
    { en: "regulator", vi: "cơ quan quản lý" },
    { en: "oversight", vi: "giám sát quản lý" },
    { en: "approval", vi: "phê chuẩn" },
    { en: "requirement", vi: "yêu cầu" },
    { en: "requirements", vi: "các yêu cầu" },
    { en: "guidance", vi: "hướng dẫn" },
    { en: "implementation", vi: "triển khai" },
    { en: "coordination", vi: "hiệp đồng" },
    { en: "interoperability", vi: "khả năng liên thông" },
    { en: "trajectory", vi: "quỹ đạo" },
    { en: "contingency", vi: "tình huống dự phòng" },
    { en: "outage", vi: "sự cố mất thiết bị" },
    { en: "session", vi: "phiên" },
    { en: "plenary", vi: "phiên toàn thể" },
    { en: "workshop", vi: "hội thảo" },
    { en: "conference", vi: "hội nghị" },
    { en: "delegate", vi: "đại biểu" },
    { en: "delegates", vi: "các đại biểu" },
    { en: "speaker", vi: "diễn giả" },
    { en: "chair", vi: "Chủ tọa" },
    { en: "question", vi: "câu hỏi" },
    { en: "questions", vi: "các câu hỏi" },
    { en: "presentation", vi: "bài trình bày" },
    { en: "timeline", vi: "lộ trình" },
    { en: "safety", vi: "an toàn" },
    { en: "risk", vi: "rủi ro" },
    { en: "report", vi: "báo cáo" },
    { en: "reports", vi: "các báo cáo" },
    { en: "voluntary", vi: "tự nguyện" },
    { en: "mandatory", vi: "bắt buộc" },
    { en: "enforcement", vi: "thực thi" },
    { en: "expectation", vi: "yêu cầu" },
    { en: "expectations", vi: "các yêu cầu" },
    { en: "meeting", vi: "cuộc họp" },
    { en: "still", vi: "vẫn" },
    { en: "while", vi: "trong khi" },
    { en: "protect", vi: "bảo vệ" },
    { en: "maintain", vi: "duy trì" },
    { en: "ensure", vi: "bảo đảm" }
  ];

  ATC.PHRASES = [
    { vi: "quản lý rủi ro mệt mỏi", en: "fatigue risk management" },
    { vi: "quản lý mệt mỏi", en: "fatigue management" },
    { vi: "hệ thống quản lý an toàn", en: "the safety management system" },
    { vi: "hệ thống quản lý rủi ro mệt mỏi", en: "the fatigue risk management system" },
    { vi: "lịch kíp trực", en: "the watch schedule" },
    { vi: "lịch ca kíp", en: "the roster" },
    { vi: "chỉnh lịch kíp trực", en: "adjusting the watch schedule" },
    { vi: "chỉnh lịch", en: "roster adjustment" },
    { vi: "đưa vào SMS", en: "integrate into the SMS" },
    { vi: "lồng ghép vào SMS", en: "embed within the SMS" },
    { vi: "năng lực khai thác", en: "operational capacity" },
    { vi: "năng lực công bố", en: "declared capacity" },
    { vi: "định biên nhân sự", en: "staffing levels" },
    { vi: "định biên", en: "staffing" },
    { vi: "thời gian trực vị trí", en: "time-in-position" },
    { vi: "thời gian làm nhiệm vụ", en: "duty time" },
    { vi: "nghỉ giải lao", en: "position relief / break" },
    { vi: "ca đêm", en: "night duty" },
    { vi: "trực chờ", en: "on-call duty" },
    { vi: "công bố lịch", en: "roster publication" },
    { vi: "văn hóa công bằng", en: "just culture" },
    { vi: "báo cáo tự nguyện", en: "voluntary reporting" },
    { vi: "báo cáo bắt buộc", en: "mandatory occurrence reporting" },
    { vi: "đánh giá rủi ro", en: "risk assessment" },
    { vi: "biện pháp kiểm soát", en: "control measures" },
    { vi: "hành động khắc phục", en: "corrective action" },
    { vi: "chỉ số hiệu suất an toàn", en: "safety performance indicators" },
    { vi: "mối nguy", en: "hazard" },
    { vi: "uy hiếp an toàn", en: "safety incident" },
    { vi: "sự cố", en: "occurrence" },
    { vi: "phê chuẩn của Cục", en: "CAAV approval" },
    { vi: "Cục Hàng không Việt Nam", en: "the Civil Aviation Authority of Viet Nam" },
    { vi: "Thông tư 47", en: "Circular 47" },
    { vi: "dẫn đường dựa trên hiệu năng", en: "performance-based navigation" },
    { vi: "hạ độ cao liên tục", en: "continuous descent operations" },
    { vi: "leo cao liên tục", en: "continuous climb operations" },
    { vi: "quản lý luồng không lưu", en: "air traffic flow management" },
    { vi: "điều hòa luồng", en: "flow management" },
    { vi: "chia sẻ thông tin toàn hệ thống", en: "system-wide information management" },
    { vi: "hiệp đồng liên trung tâm", en: "inter-centre coordination" },
    { vi: "thư thỏa thuận", en: "letter of agreement" },
    { vi: "năng định đơn vị", en: "unit endorsement" },
    { vi: "huấn luyện theo năng lực", en: "competency-based training" },
    { vi: "huấn luyện tại vị trí", en: "on-the-job training" },
    { vi: "trình độ tiếng Anh ICAO", en: "ICAO language proficiency" },
    { vi: "cấp độ 4", en: "ICAO Level 4" },
    { vi: "cấp độ 5", en: "ICAO Level 5" },
    { vi: "đoàn đại biểu", en: "the delegation" },
    { vi: "kính thưa Đoàn Chủ tịch", en: "Thank you, Chair" },
    { vi: "kính thưa chủ tọa", en: "Thank you, Chair" },
    { vi: "xin hết", en: "I thank you" },
    { vi: "đơn vị", en: "the unit" },
    { vi: "nhà cung cấp dịch vụ", en: "the service provider" },
    { vi: "kiểm soát viên không lưu", en: "air traffic controllers" },
    { vi: "nhân viên kỹ thuật", en: "technical personnel" },
    { vi: "tải việc", en: "workload" },
    { vi: "độ phức tạp", en: "complexity" },
    { vi: "giãn cách", en: "spacing" },
    { vi: "phân cách", en: "separation" },
    { vi: "đường cất hạ cánh", en: "runway" },
    { vi: "khu vực tiếp cận", en: "the TMA" },
    { vi: "trung tâm đường dài", en: "the area control centre" },
    { vi: "đài kiểm soát", en: "the control tower" },
    { vi: "bàn giao ca", en: "handover" },
    { vi: "đủ điều kiện nhận nhiệm vụ", en: "fit for duty" },
    { vi: "tự báo cáo mệt mỏi", en: "fatigue self-reporting" },
    { vi: "dữ liệu dự báo", en: "predictive data" },
    { vi: "dữ liệu chủ động", en: "proactive data" },
    { vi: "dữ liệu phản ứng", en: "reactive data" },
    { vi: "không chỉ là", en: "not merely" },
    { vi: "mới chỉ", en: "only" },
    { vi: "hay chỉ", en: "or only" },
    { vi: "xin hỏi", en: "" },
    { vi: "cho hỏi", en: "" },
    { vi: "đề nghị", en: "we propose that" },
    { vi: "chúng tôi cho rằng", en: "we consider that" },
    { vi: "về phía chúng tôi", en: "from our side" },
    { vi: "sẵn sàng chia sẻ", en: "we are ready to share" },
    { vi: "bài học kinh nghiệm", en: "operational lessons" },
    { vi: "đối tác trong khu vực", en: "partners in the region" },
    { vi: "theo Doc", en: "in accordance with Doc" },
    { vi: "theo Phụ ước", en: "in accordance with Annex" },
    { vi: "khóa học này", en: "this course" },
    { vi: "bài giảng", en: "the course material" },
    { vi: "diễn giả", en: "the distinguished speaker" },
    { vi: "câu hỏi của tôi là", en: "my question is" },
    { vi: "ý kiến phản biện", en: "a point of rebuttal" },
    { vi: "tham luận", en: "this intervention" },
    { en: "air transport", vi: "vận tải hàng không" },
    { en: "air passenger traffic", vi: "lượng hành khách hàng không" },
    { en: "passenger traffic", vi: "lượng hành khách" },
    { en: "cooperation and collaboration", vi: "hợp tác và cộng tác" },
    { en: "over decades", vi: "qua nhiều thập kỷ" },
    { en: "realistic timeline", vi: "lộ trình khả thi" },
    { en: "SWIM implementation", vi: "triển khai SWIM" },
    { en: "information exchanges", vi: "trao đổi thông tin" },
    { en: "and which information exchanges", vi: "và những trao đổi thông tin nào" },
    { en: "and which", vi: "và những" },
    { en: "operational first", vi: "đưa vào khai thác trước" },
    { en: "flight, aeronautical or weather data", vi: "dữ liệu bay, tin tức hàng không hay khí tượng" },
    { en: "weather data", vi: "dữ liệu khí tượng" },
    { en: "aeronautical", vi: "hàng không" },
    { en: "language proficiency", vi: "trình độ ngôn ngữ" },
    { en: "after initial Level 4", vi: "sau cấp độ 4 ban đầu" },
    { en: "unusual-situation phraseology", vi: "thuật ngữ tình huống bất thường" },
    { en: "unusual situation", vi: "tình huống bất thường" },
    { en: "voluntary report", vi: "báo cáo tự nguyện" },
    { en: "loss of separation", vi: "mất phân cách" },
    { en: "just culture", vi: "văn hóa công bằng" },
    { en: "enforcement expectations", vi: "yêu cầu thực thi của cơ quan quản lý" },
    { en: "coffee break", vi: "giờ giải lao" },
    { en: "remaining questions", vi: "các câu hỏi còn lại" },
    { en: "traffic demand peaks", vi: "cao điểm nhu cầu không lưu" },
    { en: "peak traffic", vi: "cao điểm không lưu" },
    { en: "if a controller", vi: "nếu kiểm soát viên" },
    { en: "files a voluntary report", vi: "nộp báo cáo tự nguyện" },
    { en: "file a voluntary report", vi: "nộp báo cáo tự nguyện" },
    { en: "files a report", vi: "nộp báo cáo" },
    { en: "file a report", vi: "nộp báo cáo" },
    { en: "after a loss of separation", vi: "sau sự cố mất phân cách" },
    { en: "how do you protect just culture", vi: "quý vị bảo vệ văn hóa công bằng thế nào" },
    { en: "how do you protect", vi: "quý vị bảo vệ thế nào" },
    { en: "while still meeting", vi: "đồng thời vẫn đáp ứng" },
    { en: "still meeting", vi: "vẫn đáp ứng" },
    { en: "meeting the", vi: "đáp ứng" },
    { en: "meeting expectations", vi: "đáp ứng các yêu cầu" },
    { en: "enforcement expectations", vi: "yêu cầu thực thi" },
    { en: "the regulator's enforcement expectations", vi: "yêu cầu thực thi của cơ quan quản lý" },
    { en: "regulator's", vi: "của cơ quan quản lý" },
    { en: "after a", vi: "sau" }
  ];

  ATC.REGEX_PHRASES = [
    {
      vi: /(?:đã|đã được)?\s*đưa (?:việc )?(?:quản lý )?(?:rủi ro )?mệt mỏi vào SMS chưa/gi,
      en: "whether fatigue risk management has already been integrated into the SMS"
    },
    {
      vi: /đưa (?:việc )?(?:quản lý )?(?:rủi ro )?mệt mỏi vào SMS/gi,
      en: "integrate fatigue risk management into the SMS"
    },
    {
      vi: /hay mới chỉ chỉnh lịch kíp trực/gi,
      en: "or whether measures are still limited to roster and watch adjustments"
    },
    {
      vi: /mới chỉ chỉnh lịch(?: kíp trực)?/gi,
      en: "limited to roster adjustments only"
    },
    {
      vi: /xin hỏi đơn vị/gi,
      en: "could the unit confirm"
    },
    {
      vi: /fatigue (?:risk )?management (?:been )?(?:put |placed |integrated )?into (?:the )?SMS/gi,
      viOut: "đã lồng ghép quản lý mệt mỏi vào SMS"
    },
    {
      vi: /only (?:changing |adjusting )?(?:the )?(?:roster|watch schedule|shift schedule)/gi,
      viOut: "mới chỉ điều chỉnh lịch kíp trực"
    }
  ];

  ATC.SAMPLES = [
    {
      id: "frms-sms",
      lang: "vi",
      topic: "sms_frms",
      label: "FRMS trong SMS",
      text: "Xin hỏi đơn vị đã đưa quản lý mệt mỏi vào SMS chưa, hay mới chỉ chỉnh lịch kíp trực?"
    },
    {
      id: "swim-en",
      lang: "en",
      topic: "swim",
      label: "SWIM timeline",
      text: "What is the realistic timeline for SWIM implementation at the ANSP, and which information exchanges will be operational first — flight, aeronautical or weather data?"
    },
    {
      id: "staffing-vi",
      lang: "vi",
      topic: "staffing",
      label: "Định biên ATCO",
      text: "Năng lực khu vực đang tăng nhưng định biên kiểm soát viên và thời gian huấn luyện năng định chưa theo kịp. Đơn vị xử lý rủi ro này thế nào?"
    },
    {
      id: "pbn-en",
      lang: "en",
      topic: "pbn",
      label: "PBN CDO",
      text: "Has the TMA implemented CDO and CCO on PBN STARs and SIDs, and how do you protect those profiles when traffic demand peaks?"
    },
    {
      id: "lpr-en",
      lang: "en",
      topic: "language",
      label: "ICAO English",
      text: "How does the unit maintain ICAO language proficiency for ATCOs after initial Level 4, especially for OJTI and unusual-situation phraseology?"
    },
    {
      id: "atfm-vi",
      lang: "vi",
      topic: "atfm_capacity",
      label: "ATFM / delay",
      text: "Khi delay tăng ở TMA, đơn vị ưu tiên điều hòa luồng bằng ATFM hay tăng năng lực công bố? Ai chịu trách nhiệm phối hợp với sân bay và hãng?"
    },
    {
      id: "just-en",
      lang: "en",
      topic: "safety",
      label: "Just culture",
      text: "If a controller files a voluntary report after a loss of separation, how do you protect just culture while still meeting the regulator’s enforcement expectations?"
    },
    {
      id: "chair-time",
      lang: "en",
      topic: "general",
      label: "Hết giờ phiên",
      text: "We have three remaining questions and only four minutes before the coffee break. How should the Chair close this item?"
    }
  ];
})(typeof globalThis !== "undefined" ? globalThis : this);
