(function (root) {
  var ATC = root.ATC || (root.ATC = {});

  /* Longer phrases first at runtime. Used for EN→VI when the browser has no on-device MT. */
  ATC.EN_VI_LEXICON = [
    ["ladies and gentlemen", "thưa quý vị"],
    ["distinguished delegates", "kính thưa quý đại biểu"],
    ["distinguished colleagues", "kính thưa quý đồng nghiệp"],
    ["distinguished guests", "kính thưa quý khách"],
    ["thank you very much", "xin trân trọng cảm ơn"],
    ["thank you, chair", "cảm ơn Chủ tọa"],
    ["thank you chair", "cảm ơn Chủ tọa"],
    ["mr chair", "thưa Chủ tọa"],
    ["madam chair", "thưa Chủ tọa"],
    ["good morning", "kính chào buổi sáng"],
    ["good afternoon", "kính chào buổi chiều"],
    ["good evening", "kính chào buổi tối"],
    ["it is my pleasure", "tôi rất hân hạnh"],
    ["i would like to", "tôi muốn"],
    ["i am pleased to", "tôi hân hạnh"],
    ["we would like to", "chúng tôi muốn"],
    ["we are pleased to", "chúng tôi hân hạnh"],
    ["on behalf of", "nhân danh"],
    ["in accordance with", "theo"],
    ["with regard to", "đối với"],
    ["in terms of", "về mặt"],
    ["in order to", "để"],
    ["as well as", "cũng như"],
    ["as soon as possible", "sớm nhất có thể"],
    ["at the same time", "đồng thời"],
    ["for example", "ví dụ"],
    ["in particular", "đặc biệt"],
    ["in this session", "trong phiên này"],
    ["in this paper", "trong bài này"],
    ["in this presentation", "trong bài trình bày này"],
    ["today i will", "hôm nay tôi sẽ"],
    ["today we will", "hôm nay chúng tôi sẽ"],
    ["i will talk about", "tôi sẽ nói về"],
    ["we will talk about", "chúng tôi sẽ nói về"],
    ["i will discuss", "tôi sẽ thảo luận"],
    ["we will discuss", "chúng tôi sẽ thảo luận"],
    ["let me begin", "xin phép bắt đầu"],
    ["let me turn to", "xin chuyển sang"],
    ["first of all", "trước hết"],
    ["last but not least", "cuối cùng nhưng không kém phần quan trọng"],
    ["to conclude", "để kết luận"],
    ["in conclusion", "kết luận"],
    ["the purpose of this", "mục đích của"],
    ["the objective of", "mục tiêu của"],
    ["key challenges", "những thách thức chính"],
    ["best practice", "thông lệ tốt"],
    ["best practices", "các thông lệ tốt"],
    ["lessons learned", "bài học kinh nghiệm"],
    ["way forward", "hướng đi tiếp"],
    ["next steps", "các bước tiếp theo"],
    ["action plan", "kế hoạch hành động"],
    ["implementation plan", "kế hoạch triển khai"],
    ["road map", "lộ trình"],
    ["roadmap", "lộ trình"],
    ["time frame", "khung thời gian"],
    ["timeframe", "khung thời gian"],
    ["realistic timeline", "lộ trình khả thi"],
    ["member states", "các quốc gia thành viên"],
    ["contracting states", "các quốc gia thành viên"],
    ["working group", "nhóm công tác"],
    ["task force", "tổ công tác"],
    ["plenary session", "phiên toàn thể"],
    ["side event", "sự kiện bên lề"],
    ["coffee break", "giờ giải lao"],
    ["question and answer", "hỏi đáp"],
    ["q and a", "hỏi đáp"],
    ["point of order", "ý kiến về thủ tục"],
    ["take the floor", "xin phát biểu"],
    ["give the floor", "mời phát biểu"],
    ["i give the floor", "tôi mời phát biểu"],
    ["the distinguished speaker", "diễn giả"],
    ["air navigation", "dẫn đường hàng không"],
    ["civil aviation", "hàng không dân dụng"],
    ["air transport", "vận tải hàng không"],
    ["air passenger traffic", "lượng hành khách hàng không"],
    ["passenger traffic", "lượng hành khách"],
    ["cooperation, collaboration and standardization", "hợp tác, cộng tác và tiêu chuẩn hóa"],
    ["cooperation and collaboration", "hợp tác và cộng tác"],
    ["collaboration and standardization", "cộng tác và tiêu chuẩn hóa"],
    ["has ensured that", "đã bảo đảm rằng"],
    ["contributes to safety", "góp phần cho an toàn"],
    ["this framework", "khung này"],
    ["today we will discuss", "hôm nay chúng tôi sẽ thảo luận"],
    ["safety and capacity", "an toàn và năng lực"],
    ["in the tma", "trong khu TMA"],
    ["over decades", "qua nhiều thập kỷ"],
    ["flight safety", "an toàn bay"],
    ["aviation safety", "an toàn hàng không"],
    ["operational safety", "an toàn khai thác"],
    ["safety risk", "rủi ro an toàn"],
    ["risk assessment", "đánh giá rủi ro"],
    ["risk management", "quản lý rủi ro"],
    ["change management", "quản lý thay đổi"],
    ["human factors", "yếu tố con người"],
    ["fatigue management", "quản lý mệt mỏi"],
    ["watch schedule", "lịch kíp trực"],
    ["shift schedule", "lịch ca"],
    ["training programme", "chương trình huấn luyện"],
    ["training program", "chương trình huấn luyện"],
    ["language proficiency", "trình độ ngôn ngữ"],
    ["unusual situation", "tình huống bất thường"],
    ["loss of separation", "mất phân cách"],
    ["just culture", "văn hóa công bằng"],
    ["voluntary report", "báo cáo tự nguyện"],
    ["traffic demand", "nhu cầu không lưu"],
    ["peak traffic", "cao điểm không lưu"],
    ["declared capacity", "năng lực công bố"],
    ["what is the", "đâu là"],
    ["what are the", "đâu là"],
    ["how do we", "chúng ta làm sao"],
    ["how do you", "quý vị làm sao"],
    ["how does the", "làm sao"],
    ["how can we", "chúng ta có thể làm sao"],
    ["how can the", "làm sao"],
    ["could you please", "xin quý vị"],
    ["could you", "quý vị có thể"],
    ["can you please", "xin quý vị"],
    ["i have a question", "tôi có một câu hỏi"],
    ["my question is", "câu hỏi của tôi là"],
    ["we believe that", "chúng tôi cho rằng"],
    ["we consider that", "chúng tôi xét thấy"],
    ["we propose that", "chúng tôi đề nghị"],
    ["we recommend that", "chúng tôi khuyến nghị"],
    ["we suggest that", "chúng tôi đề xuất"],
    ["it is important to", "điều quan trọng là"],
    ["it is necessary to", "cần phải"],
    ["we need to", "chúng ta cần"],
    ["we have to", "chúng ta phải"],
    ["we must", "chúng ta phải"],
    ["we should", "chúng ta nên"],
    ["we can", "chúng ta có thể"],
    ["we will", "chúng tôi sẽ"],
    ["we are", "chúng tôi"],
    ["they are", "họ"],
    ["there is", "có"],
    ["there are", "có"],
    ["this is", "đây là"],
    ["that is", "đó là"],
    ["these are", "đây là"],
    ["those are", "đó là"],
    ["has been", "đã được"],
    ["have been", "đã được"],
    ["has the", "đã"],
    ["have you", "quý vị đã"],
    ["will be", "sẽ được"],
    ["should be", "nên được"],
    ["must be", "phải được"],
    ["can be", "có thể được"],
    ["cannot be", "không thể được"],
    ["do not", "không"],
    ["does not", "không"],
    ["did not", "đã không"],
    ["is not", "không phải"],
    ["are not", "không"],
    ["was not", "đã không"],
    ["were not", "đã không"],
    ["will not", "sẽ không"],
    ["cannot", "không thể"],
    ["won't", "sẽ không"],
    ["don't", "không"],
    ["doesn't", "không"],
    ["didn't", "đã không"],
    ["isn't", "không phải"],
    ["aren't", "không"],
    ["wasn't", "đã không"],
    ["weren't", "đã không"],
    ["we're", "chúng tôi"],
    ["they're", "họ"],
    ["it's", "đây là"],
    ["that's", "đó là"],
    ["there's", "có"],
    ["i'm", "tôi"],
    ["let's", "chúng ta hãy"],
    ["according to", "theo"],
    ["based on", "dựa trên"],
    ["due to", "do"],
    ["such as", "như"],
    ["rather than", "thay vì"],
    ["more than", "hơn"],
    ["less than", "ít hơn"],
    ["at least", "ít nhất"],
    ["not only", "không chỉ"],
    ["but also", "mà còn"],
    ["in addition", "ngoài ra"],
    ["however", "tuy nhiên"],
    ["therefore", "do đó"],
    ["moreover", "hơn nữa"],
    ["furthermore", "hơn nữa"],
    ["meanwhile", "đồng thời"],
    ["currently", "hiện nay"],
    ["recently", "gần đây"],
    ["today", "hôm nay"],
    ["yesterday", "hôm qua"],
    ["tomorrow", "ngày mai"],
    ["this year", "năm nay"],
    ["next year", "năm tới"],
    ["this morning", "sáng nay"],
    ["this afternoon", "chiều nay"],
    ["implementation", "việc triển khai"],
    ["implemented", "đã triển khai"],
    ["implement", "triển khai"],
    ["coordination", "hiệp đồng"],
    ["cooperation", "hợp tác"],
    ["collaboration", "cộng tác"],
    ["information", "thông tin"],
    ["operation", "khai thác"],
    ["operations", "khai thác"],
    ["operational", "về khai thác"],
    ["procedure", "thủ tục"],
    ["procedures", "các thủ tục"],
    ["requirement", "yêu cầu"],
    ["requirements", "các yêu cầu"],
    ["regulation", "quy định"],
    ["regulations", "các quy định"],
    ["guidance", "hướng dẫn"],
    ["standard", "tiêu chuẩn"],
    ["standards", "các tiêu chuẩn"],
    ["performance", "hiệu năng"],
    ["efficiency", "hiệu quả"],
    ["capacity", "năng lực"],
    ["workload", "tải việc"],
    ["complexity", "độ phức tạp"],
    ["staffing", "định biên"],
    ["training", "huấn luyện"],
    ["competency", "năng lực chuyên môn"],
    ["proficiency", "trình độ"],
    ["fatigue", "mệt mỏi"],
    ["safety", "an toàn"],
    ["security", "an ninh"],
    ["quality", "chất lượng"],
    ["timeline", "lộ trình thời gian"],
    ["schedule", "lịch"],
    ["delay", "chậm"],
    ["delays", "chậm chuyến"],
    ["congestion", "tắc nghẽn"],
    ["throughput", "lưu lượng thông qua"],
    ["sector", "khu vực"],
    ["sectors", "các khu vực"],
    ["unit", "đơn vị"],
    ["units", "các đơn vị"],
    ["provider", "nhà cung cấp"],
    ["providers", "các nhà cung cấp"],
    ["regulator", "cơ quan quản lý"],
    ["authority", "cơ quan"],
    ["delegation", "đoàn đại biểu"],
    ["conference", "hội nghị"],
    ["workshop", "hội thảo"],
    ["symposium", "hội thảo chuyên đề"],
    ["presentation", "bài trình bày"],
    ["speaker", "diễn giả"],
    ["question", "câu hỏi"],
    ["questions", "các câu hỏi"],
    ["answer", "câu trả lời"],
    ["comment", "ý kiến"],
    ["comments", "các ý kiến"],
    ["proposal", "đề xuất"],
    ["recommendation", "khuyến nghị"],
    ["challenge", "thách thức"],
    ["challenges", "các thách thức"],
    ["issue", "vấn đề"],
    ["issues", "các vấn đề"],
    ["problem", "vấn đề"],
    ["priority", "ưu tiên"],
    ["priorities", "các ưu tiên"],
    ["benefit", "lợi ích"],
    ["benefits", "các lợi ích"],
    ["progress", "tiến độ"],
    ["status", "tình trạng"],
    ["update", "cập nhật"],
    ["support", "hỗ trợ"],
    ["improve", "cải thiện"],
    ["improved", "đã cải thiện"],
    ["improvement", "cải thiện"],
    ["enhance", "tăng cường"],
    ["enhanced", "đã tăng cường"],
    ["maintain", "duy trì"],
    ["ensure", "bảo đảm"],
    ["protect", "bảo vệ"],
    ["reduce", "giảm"],
    ["increase", "tăng"],
    ["develop", "xây dựng"],
    ["development", "phát triển"],
    ["provide", "cung cấp"],
    ["require", "yêu cầu"],
    ["required", "được yêu cầu"],
    ["consider", "xem xét"],
    ["continue", "tiếp tục"],
    ["introduce", "giới thiệu"],
    ["explain", "giải thích"],
    ["describe", "mô tả"],
    ["highlight", "nhấn mạnh"],
    ["address", "xử lý"],
    ["share", "chia sẻ"],
    ["report", "báo cáo"],
    ["discuss", "thảo luận"],
    ["discussion", "thảo luận"],
    ["focus", "tập trung"],
    ["include", "bao gồm"],
    ["including", "bao gồm"],
    ["using", "sử dụng"],
    ["used", "được sử dụng"],
    ["need", "cần"],
    ["needs", "cần"],
    ["needed", "cần"],
    ["important", "quan trọng"],
    ["necessary", "cần thiết"],
    ["possible", "có thể"],
    ["available", "sẵn có"],
    ["effective", "hiệu quả"],
    ["efficient", "hiệu suất cao"],
    ["realistic", "khả thi"],
    ["further", "tiếp theo"],
    ["additional", "bổ sung"],
    ["current", "hiện nay"],
    ["future", "tương lai"],
    ["regional", "khu vực"],
    ["national", "quốc gia"],
    ["international", "quốc tế"],
    ["global", "toàn cầu"],
    ["local", "địa phương"],
    ["please", "xin"],
    ["thank you", "xin cảm ơn"],
    ["thanks", "cảm ơn"],
    ["yes", "vâng"],
    ["no", "không"],
    ["also", "cũng"],
    ["very", "rất"],
    ["more", "thêm"],
    ["most", "phần lớn"],
    ["many", "nhiều"],
    ["some", "một số"],
    ["any", "bất kỳ"],
    ["all", "tất cả"],
    ["both", "cả"],
    ["each", "mỗi"],
    ["other", "khác"],
    ["new", "mới"],
    ["old", "cũ"],
    ["first", "thứ nhất"],
    ["second", "thứ hai"],
    ["third", "thứ ba"],
    ["finally", "cuối cùng"],
    ["now", "hiện nay"],
    ["then", "sau đó"],
    ["here", "ở đây"],
    ["there", "ở đó"],
    ["when", "khi"],
    ["where", "nơi"],
    ["which", "nào"],
    ["whose", "của"],
    ["why", "vì sao"],
    ["how", "như thế nào"],
    ["who", "ai"],
    ["from", "từ"],
    ["with", "với"],
    ["without", "không có"],
    ["into", "vào"],
    ["onto", "lên"],
    ["upon", "về"],
    ["about", "về"],
    ["after", "sau"],
    ["before", "trước"],
    ["during", "trong"],
    ["between", "giữa"],
    ["among", "trong"],
    ["through", "thông qua"],
    ["under", "dưới"],
    ["over", "trên"],
    ["within", "trong"],
    ["across", "trên"],
    ["against", "trước"],
    ["toward", "hướng tới"],
    ["towards", "hướng tới"],
    ["because", "bởi vì"],
    ["although", "mặc dù"],
    ["while", "trong khi"],
    ["whether", "liệu"],
    ["if", "nếu"],
    ["and", "và"],
    ["or", "hoặc"],
    ["but", "nhưng"],
    ["not", "không"],
    ["only", "chỉ"],
    ["just", "chỉ"],
    ["still", "vẫn"],
    ["already", "đã"],
    ["always", "luôn"],
    ["often", "thường"],
    ["also", "cũng"],
    ["our", "của chúng tôi"],
    ["your", "của quý vị"],
    ["their", "của họ"],
    ["its", "của"],
    ["his", "của"],
    ["her", "của"],
    ["my", "của tôi"],
    ["we", "chúng tôi"],
    ["you", "quý vị"],
    ["they", "họ"],
    ["he", "ông ấy"],
    ["she", "bà ấy"],
    ["i", "tôi"],
    ["is", "là"],
    ["are", "là"],
    ["was", "đã"],
    ["were", "đã"],
    ["be", "được"],
    ["been", "đã được"],
    ["being", "đang"],
    ["have", "có"],
    ["has", "đã"],
    ["had", "đã"],
    ["do", ""],
    ["does", ""],
    ["did", "đã"],
    ["will", "sẽ"],
    ["would", "sẽ"],
    ["can", "có thể"],
    ["could", "có thể"],
    ["should", "nên"],
    ["must", "phải"],
    ["may", "có thể"],
    ["might", "có thể"],
    ["shall", "sẽ"],
    ["of", "của"],
    ["in", "trong"],
    ["on", "trên"],
    ["at", "tại"],
    ["for", "cho"],
    ["to", ""],
    ["by", "bởi"]
  ];
})(typeof globalThis !== "undefined" ? globalThis : this);
