from __future__ import annotations

from .concept import PhraseologyRule, Severity
from .parse import Template

TEMPLATES = [
    Template(
        template_id="TPL_CLIMB_FL",
        intent="CLIMB",
        role="BOTH",
        regex=r"(?P<cs>[a-z0-9 ]+)?\s*climb(?:ing)?(?: and maintain)?(?: to)?(?: flight level| fl) (?P<fl>[0-9 ]+)",
        param_map={"fl": "level"},
        must_readback=True,
    ),
    Template(
        template_id="TPL_DESCEND_FL",
        intent="DESCEND",
        role="BOTH",
        regex=r"(?P<cs>[a-z0-9 ]+)?\s*descend(?:ing)?(?: and maintain)?(?: to)?(?: flight level| fl) (?P<fl>[0-9 ]+)",
        param_map={"fl": "level"},
        must_readback=True,
    ),
    Template(
        template_id="TPL_MAINTAIN_FL",
        intent="MAINTAIN",
        role="BOTH",
        regex=r"(?P<cs>[a-z0-9 ]+)?\s*maintain(?: flight level| fl) (?P<fl>[0-9 ]+)",
        param_map={"fl": "level"},
        must_readback=True,
    ),
    Template(
        template_id="TPL_HEADING",
        intent="FLY_HEADING",
        role="BOTH",
        regex=r"(?:turn (?:left|right) heading|fly heading|heading) (?P<hdg>[0-9 ]{3,12})",
        param_map={"hdg": "heading"},
        must_readback=True,
    ),
    Template(
        template_id="TPL_SQUAWK",
        intent="SQUAWK",
        role="BOTH",
        regex=r"squawk (?P<code>[0-9 ]{4,15})",
        param_map={"code": "squawk"},
        must_readback=True,
    ),
    Template(
        template_id="TPL_CONTACT",
        intent="CONTACT",
        role="BOTH",
        regex=r"contact (?P<unit>[a-z ]+) (?P<freq>[0-9]+(?: decimal [0-9]+)?|[0-9]+\.[0-9]+)",
        param_map={"freq": "freq"},
        must_readback=True,
    ),
    Template(
        template_id="TPL_QNH",
        intent="QNH",
        role="BOTH",
        regex=r"qnh (?P<qnh>[0-9 ]{4,12})",
        param_map={"qnh": "qnh"},
        must_readback=True,
    ),
    Template(
        template_id="TPL_HOLD_SHORT",
        intent="HOLD_SHORT",
        role="BOTH",
        regex=r"hold short (?:of )?runway (?P<rwy>[0-9]{2}[lrc]?)",
        param_map={"rwy": "runway"},
        must_readback=True,
    ),
    Template(
        template_id="TPL_CLEARED_TO",
        intent="CLEARED_TAKEOFF",
        role="BOTH",
        regex=r"runway (?P<rwy>[0-9]{2}[lrc]?) cleared for take-?off",
        param_map={"rwy": "runway"},
        must_readback=True,
    ),
    Template(
        template_id="TPL_CLEARED_LAND",
        intent="CLEARED_LAND",
        role="BOTH",
        regex=r"runway (?P<rwy>[0-9]{2}[lrc]?) cleared to land",
        param_map={"rwy": "runway"},
        must_readback=True,
    ),
    Template(
        template_id="TPL_SPEED",
        intent="SPEED",
        role="BOTH",
        regex=r"(?:reduce |increase |maintain )?speed (?P<spd>[0-9 ]+)\s*(?:knots|kt)?",
        param_map={"spd": "speed"},
        must_readback=True,
    ),
    Template(
        template_id="TPL_LINE_UP",
        intent="LINE_UP",
        role="BOTH",
        regex=r"line up(?: and wait)?(?: runway (?P<rwy>[0-9]{2}[lrc]?))?",
        param_map={"rwy": "runway"},
        must_readback=True,
    ),
    Template(
        template_id="TPL_CLEARED_APP",
        intent="CLEARED_APPROACH",
        role="BOTH",
        regex=r"cleared (?:the )?(?:ils |rnav |vor |visual )?approach(?: runway (?P<rwy>[0-9]{2}[lrc]?))?",
        param_map={"rwy": "runway"},
        must_readback=True,
    ),
]

RULES = [
    PhraseologyRule(
        rule_id="R_LEVEL_MUST",
        intent="*",
        field="level",
        severity=Severity.RED,
        compare_fn="numeric",
        required_when="ALWAYS",
        source_doc="DOC4444",
        source_clause="4.5.7.5 / Annex 11 3.7.3.1",
        description_vi="Mức bay / độ cao trong huấn lệnh phải được readback đúng số và đúng đơn vị (FL vs feet).",
        description_en="Level instructions shall be read back with correct value and unit.",
    ),
    PhraseologyRule(
        rule_id="R_HEADING_MUST",
        intent="FLY_HEADING",
        field="heading",
        severity=Severity.AMBER,
        compare_fn="heading_deg",
        required_when="ALWAYS",
        source_doc="DOC4444",
        source_clause="Annex 11 3.7.3.1",
        description_vi="Hướng bay phải readback đủ 3 chữ số.",
        description_en="Heading instructions shall be read back.",
    ),
    PhraseologyRule(
        rule_id="R_SQUAWK_MUST",
        intent="SQUAWK",
        field="squawk",
        severity=Severity.RED,
        compare_fn="exact_norm",
        required_when="ALWAYS",
        source_doc="DOC4444",
        source_clause="Annex 11 3.7.3.1",
        description_vi="Mã SSR 4 số phải readback nguyên vẹn (bắt đảo số).",
        description_en="SSR codes shall be read back in full.",
    ),
    PhraseologyRule(
        rule_id="R_FREQ_MUST",
        intent="CONTACT",
        field="freq",
        severity=Severity.AMBER,
        compare_fn="freq_mhz",
        required_when="ALWAYS",
        source_doc="DOC4444",
        source_clause="Annex 11 3.7.3.1",
        description_vi="Tần số liên lạc phải readback.",
        description_en="Frequency change shall be read back.",
    ),
    PhraseologyRule(
        rule_id="R_QNH_MUST",
        intent="QNH",
        field="qnh",
        severity=Severity.AMBER,
        compare_fn="numeric",
        required_when="ALWAYS",
        source_doc="DOC4444",
        source_clause="Annex 11 3.7.3.1",
        description_vi="QNH/QFE phải readback.",
        description_en="Altimeter settings shall be read back.",
    ),
    PhraseologyRule(
        rule_id="R_RWY_MUST",
        intent="*",
        field="runway",
        severity=Severity.RED,
        compare_fn="exact_norm",
        required_when="ALWAYS",
        source_doc="DOC4444",
        source_clause="Annex 11 3.7.3.1 b",
        description_vi="Hold short / cross / enter / take-off / land trên đường cất hạ cánh phải readback đầy đủ số đường CHC.",
        description_en="Runway-related clearances shall be read back in full.",
    ),
    PhraseologyRule(
        rule_id="R_ROGER_NOT_RB",
        intent=None,
        field="*",
        severity=Severity.AMBER,
        compare_fn="ack_only",
        required_when="IF_PRESENT_IN_ATCO",
        source_doc="DOC4444",
        source_clause="4.5.7.5",
        description_vi="Roger/Wilco không thay thế readback số liệu an toàn.",
        description_en="Roger/Wilco is not an acceptable substitute for readback of safety-related items.",
    ),
    PhraseologyRule(
        rule_id="R_CALLSIGN_CLOSE",
        intent="*",
        field="callsign",
        severity=Severity.RED,
        compare_fn="callsign_fuzzy",
        required_when="ALWAYS",
        source_doc="DOC4444",
        source_clause="12 / callsign",
        description_vi="Readback phải kết thúc bằng đúng callsign tàu bay.",
        description_en="Readback should be terminated by the aircraft call sign.",
    ),
    PhraseologyRule(
        rule_id="R_SPEED_MUST",
        intent="SPEED",
        field="speed",
        severity=Severity.AMBER,
        compare_fn="numeric",
        required_when="ALWAYS",
        source_doc="DOC4444",
        source_clause="12 / speed",
        description_vi="Tốc độ phải readback đúng số.",
        description_en="Speed instructions shall be read back.",
    ),
]

TEACHING = {
    "MISMATCH": "Read back the exact value and unit. Do not round or substitute a nearby figure.",
    "OMISSION": "Every safety item in the clearance must appear in the readback, not only the callsign.",
    "MISSING_READBACK": "A mandatory item (level, runway, squawk, QNH, heading, speed, frequency) needs a timely readback.",
    "NON_STANDARD": "Roger / Wilco acknowledges the transmission; it does not read back the numbers.",
    "CALLSIGN_ERROR": "Close the readback with the correct aircraft call sign.",
}
