const assert = require('node:assert/strict');
require('../web/js/floating-subtitles.js');
const tick = () => new Promise(resolve => setImmediate(resolve));
(async () => {
  const calls = [], frames = [];
  let time = 0;
  const stream = ATC.createCaptionStream((text, opts) => new Promise((resolve, reject) => {
    calls.push({ text, opts, resolve, reject });
  }), frame => frames.push(frame), () => time);
  const opts = { source: 'en', sessionTopic: 'auto' };
  stream.push('First caption', opts);
  await tick();
  stream.push('Intermediate caption', opts);
  stream.push('Latest caption', opts);
  assert.equal(calls.length, 1);
  calls[0].resolve({text: 'Bản cũ', method: 'on-device-mt'});
  await tick();
  assert.equal(calls.length, 2);
  assert.equal(calls[1].text, 'Latest caption');
  assert.ok(!frames.some(f => f.translation === 'Bản cũ'));
  time = 740;
  calls[1].resolve({text: 'Bản mới', method: 'on-device-mt'});
  await tick();
  assert.equal(frames.at(-1).lag, 740);
  stream.push('Latest caption', opts);
  await tick();
  assert.equal(calls.length, 2);
  stream.push('Correction', opts);
  await tick();
  stream.reset();
  calls[2].resolve({text: 'Stale after clear'});
  await tick();
  assert.equal(frames.at(-1).text, '');
  stream.push('Recovery', opts);
  await tick();
  calls[3].reject(new Error('model unavailable'));
  await tick();
  assert.equal(frames.at(-1).error, true);
  stream.push('one two three four five six seven eight nine ten eleven twelve thirteen fourteen', opts);
  await tick();
  assert.equal(calls[4].text, 'thirteen fourteen');
  calls[4].resolve({text: 'mười ba mười bốn'});
  await tick();
  console.log('PASS: bounded queue, stale results, latency, deduplication, clear, failure recovery, short captions');
})().catch(err => { console.error(err); process.exitCode = 1; });
